spring.application.name=menu-service

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger.ui.html

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
